# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-22 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.BooleanField(default=True)),
                ('s', models.BooleanField(default=True)),
                ('l', models.BooleanField(default=False)),
                ('x', models.BooleanField(default=False)),
                ('u', models.BooleanField(default=False)),
                ('m', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='regex',
            name='flags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='regex.Flags'),
        ),
    ]
