# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-22 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regex', '0002_auto_20200822_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regex',
            name='flags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regex.Flags'),
        ),
    ]
