# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-22 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regex', '0003_auto_20200822_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flags',
            name='l',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='flags',
            name='s',
            field=models.BooleanField(default=False),
        ),
    ]
